name: Dart

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  ROOT_DIR: MEMO/App/memo # Specify your root directory here
  TEST_BRANCH: DevTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ env.ROOT_DIR }}

      - name: Analyze project source
        run: dart analyze
        working-directory: ${{ env.ROOT_DIR }}

      - name: Run tests
        run: dart test
        working-directory: ${{ env.ROOT_DIR }}

  merge-to-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.ROOT_DIR }}

      - name: Merge changes into test branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout ${{ env.TEST_BRANCH }}
          git merge ${{ github.ref }} --no-ff -m "Auto-merge from ${{ github.ref }}"
        working-directory: ${{ env.ROOT_DIR }}

  auto-merge:
    runs-on: ubuntu-latest
    needs: merge-to-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.ROOT_DIR }}

      - name: Merge changes into other branches
        uses: peter-evans/merge@v2
        with:
          source_branch: ${{ env.TEST_BRANCH }}
          target_branch: "Sandinu, Thisas, malsha, monali, sachin, sadinsa" # List your branches here
          method: merge
          commit_message: "Auto-merge from test"
          merge_method: merge
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          working-directory: ${{ env.ROOT_DIR }}
